# Generated by Django 3.2.8 on 2021-11-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproviders',
            old_name='fullname',
            new_name='name',
        ),
    ]
