# Generated by Django 3.2.8 on 2021-11-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0002_rename_fullname_serviceproviders_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviders',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
