# Generated by Django 3.2.8 on 2021-11-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0003_alter_serviceproviders_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviders',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceproviders',
            name='sptell',
            field=models.CharField(max_length=15),
        ),
    ]
