# Generated by Django 3.2.8 on 2021-11-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0004_auto_20211102_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproviders',
            old_name='spimage',
            new_name='spimagename',
        ),
        migrations.AddField(
            model_name='serviceproviders',
            name='spimageurl',
            field=models.TextField(default='-'),
        ),
    ]
