# Generated by Django 3.2.8 on 2021-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0005_auto_20211102_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviders',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
