# Generated by Django 3.2.8 on 2021-10-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='catid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='catname',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='articles',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
