# Generated by Django 3.2.8 on 2021-10-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20211025_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='time',
            field=models.CharField(default='00:00', max_length=12),
        ),
    ]
