# Generated by Django 3.2.8 on 2021-10-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='ocatid',
            field=models.IntegerField(default=0),
        ),
    ]
