# Generated by Django 3.2.8 on 2021-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='vidurl',
            field=models.TextField(default='-'),
        ),
    ]
