# Generated by Django 3.2.8 on 2021-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_gallerypost_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='height',
            field=models.IntegerField(default=4),
        ),
    ]
