# Generated by Django 3.2.8 on 2021-11-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_gallerypost_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='height',
            field=models.CharField(choices=[('col-md-4', 'col-md-4'), ('col-md-8', 'col-md-8')], default='col-md-4', max_length=10),
        ),
    ]
