# Generated by Django 3.2.8 on 2021-11-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_gallerypost_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypost',
            name='height',
        ),
        migrations.AddField(
            model_name='gallerypost',
            name='cssclass',
            field=models.CharField(choices=[('col-md-4', 'col-md-4'), ('col-md-6', 'col-md-6'), ('col-md-8', 'col-md-8'), ('col-md-10', 'col-md-10')], default='col-md-4', max_length=10),
        ),
    ]
