# Generated by Django 3.2.8 on 2021-11-12 14:40

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20211112_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypost',
            name='cssclass',
        ),
        migrations.AddField(
            model_name='gallerypost',
            name='CssClass',
            field=models.CharField(choices=[('col-md-4', 'col-md-4'), ('col-md-6', 'col-md-6'), ('col-md-8', 'col-md-8'), ('col-md-10', 'col-md-10'), ('col-md-12', 'col-md-12')], default='col-md-4', max_length=10),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='ImageOrVideo',
            field=models.FileField(upload_to='gallery/', validators=[gallery.models.validate_file_extension]),
        ),
    ]
