# Generated by Django 3.2.8 on 2021-10-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
